(() => {
  if (['localhost','127.0.0.1'].includes(location.hostname) || window.autobarMarketing) return;
  const tiktokPixel='DAT8TNJC77U5PB60DTT0',metaPixel='969483765461099',products={autobar:'cc63486e-33dc-445a-acdf-8f93cdac3cf8',agrobar:'c4a64980-0d6e-4f27-a79f-db44118b2d5b'},prefix='autobar-marketing:';
  const adsApi='https://personalizecar.vercel.app/api/autobar?action=ads',funnelEvents=new Set(['ViewContent','AddToCart','InitiateCheckout','AddPaymentInfo']);
  const seen=id=>sessionStorage.getItem(prefix+id)==='1',mark=id=>sessionStorage.setItem(prefix+id,'1');
  !function(w,d,t){w.TiktokAnalyticsObject=t;let q=w[t]=w[t]||[];q.methods=['page','track','identify','instances','debug','on','off','once','ready','alias','group','enableCookie','disableCookie','holdConsent','revokeConsent','grantConsent'];q.setAndDefer=function(target,name){target[name]=function(){target.push([name].concat(Array.prototype.slice.call(arguments,0)))}};for(let i=0;i<q.methods.length;i++)q.setAndDefer(q,q.methods[i]);q.instance=function(id){let instance=q._i[id]||[];for(let i=0;i<q.methods.length;i++)q.setAndDefer(instance,q.methods[i]);return instance};q.load=function(id){let el=d.createElement('script');q._i=q._i||{};q._i[id]=[];q._i[id]._u='https://analytics.tiktok.com/i18n/pixel/events.js';q._t=q._t||{};q._t[id]=Date.now();q._o=q._o||{};q._o[id]={};el.async=true;el.src='https://analytics.tiktok.com/i18n/pixel/events.js?sdkid='+id+'&lib='+t;d.head.append(el)};q.load(tiktokPixel);q.page()}(window,document,'ttq');
  !function(w,d,s,u){if(w.fbq)return;let f=w.fbq=function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments)};if(!w._fbq)w._fbq=f;f.push=f;f.queue=[];f.loaded=true;f.version='2.0';let el=d.createElement(s);el.async=true;el.src=u;d.head.append(el)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
  window.fbq('init',metaPixel);window.fbq('trackSingle',metaPixel,'PageView');
  const cartItems=()=>{try{const items=JSON.parse(localStorage.getItem('store:cart')||'[]');return Array.isArray(items)?items:[]}catch{return []}};
  const currentSlug=()=>location.pathname==='/produto/agrobar'?'agrobar':'autobar';
  const props=amount=>{const slugs=location.pathname==='/checkout'||location.pathname==='/pagamento-pix'?[...new Set(cartItems().map(item=>item.slug).filter(slug=>products[slug]))]:[currentSlug()];const ids=slugs.map(slug=>products[slug]);return {content_id:ids[0]||products.autobar,content_ids:ids.length?ids:[products.autobar],content_type:'product',currency:'BRL',...(Number.isFinite(amount)&&amount>0?{value:amount}:{}),product_name:slugs.map(slug=>slug==='agrobar'?'AgroBar':'GelaBar').join(' + ')||'GelaBar',store_name:'GelaBar'}};
  const cartValue=()=>{const cents=cartItems().reduce((sum,item)=>sum+Number(item.price)*Number(item.quantity),0);return Number.isFinite(cents)&&cents>0?cents/100:79};
  const action=key=>{let id=sessionStorage.getItem(prefix+'action:'+key);if(!id){id=crypto.randomUUID();sessionStorage.setItem(prefix+'action:'+key,id)}return id};
  const cookie=name=>document.cookie.split('; ').find(part=>part.startsWith(name+'='))?.slice(name.length+1)||'';
  const attribution=()=>{try{return JSON.parse(sessionStorage.getItem('autobar_attribution')||'{}')}catch{return {}}};
  const eventItems=event=>event==='ViewContent'?[{id:products[currentSlug()],slug:currentSlug(),price:7900,quantity:1}]:cartItems().filter(item=>products[item.slug]===item.id).map(item=>({id:item.id,slug:item.slug,price:item.kitQty>=2?11900:7900,quantity:Math.min(5,Math.max(1,Number(item.quantity)||1))}));
  let identity={},flushing=false;try{identity=JSON.parse(sessionStorage.getItem(prefix+'identity')||'{}')}catch{}
  async function flush(){if(flushing||navigator.onLine===false)return;flushing=true;try{const keys=[];for(let i=0;i<sessionStorage.length;i++){const key=sessionStorage.key(i);if(key?.startsWith(prefix+'pending:'))keys.push(key)}for(const key of keys){const record=JSON.parse(sessionStorage.getItem(key)||'null');if(!record)continue;if(Date.now()/1000-record.event_time>47*3600){sessionStorage.removeItem(key);continue}try{const a=attribution(),response=await fetch(adsApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...record,attribution:a,context:{...a,...identity,fbp:cookie('_fbp')||a.fbp,fbc:cookie('_fbc')||a.fbc,ttp:cookie('_ttp')||a.ttp}}),keepalive:true,signal:AbortSignal.timeout(7000)});if(response.ok&&(await response.json()).event_id===record.event_id)sessionStorage.removeItem(key)}catch{}}}catch{}finally{flushing=false}}
  const sha=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(byte=>byte.toString(16).padStart(2,'0')).join('');
  async function identify(customer){const email=String(customer.email||'').trim().toLowerCase(),phone=String(customer.phone||'').replace(/\D/g,''),document=String(customer.document||'').replace(/\D/g,''),next={};if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email=await sha(email);if(/^[1-9]{2}\d{8,9}$/.test(phone)){next.phone=await sha('+55'+phone);next.meta_phone=await sha('55'+phone);}if(/^\d{11}$|^\d{14}$/.test(document))next.external_id=await sha(document);identity=next;sessionStorage.setItem(prefix+'identity',JSON.stringify(next));try{window.ttq.identify({email:next.email,phone_number:next.phone,external_id:next.external_id})}catch{}}
  function track(event,id,amount){if(seen(event+'_'+id))return;const eventId=event+'_'+id,data=props(amount);try{window.ttq.track(event,data,{event_id:eventId})}catch{}try{window.fbq('trackSingle',metaPixel,event,data,{eventID:eventId})}catch{}mark(eventId);if(funnelEvents.has(event)){const selected=eventItems(event);if(selected.length){const page=location.pathname==='/produto/agrobar'?'agrobar':location.pathname==='/produto/autobar'?'autobar':location.pathname==='/pagamento-pix'?'payment':'checkout';sessionStorage.setItem(prefix+'pending:'+eventId,JSON.stringify({event,event_id:eventId,action_id:id,event_time:Math.floor(Date.now()/1000),items:selected,page}));void flush()}}}
  const session=()=>{let id=sessionStorage.getItem('autobar_session');if(!id){id=crypto.randomUUID();sessionStorage.setItem('autobar_session',id)}return id};
  function route(){if(['/produto/autobar','/produto/agrobar'].includes(location.pathname))track('ViewContent',action('view:'+currentSlug()),79);if(location.pathname==='/checkout')track('InitiateCheckout',action('checkout'),cartValue())}
  window.autobarMarketing={track,identify,paymentStarted:amount=>track('AddPaymentInfo',action('payment'),Number(amount)/100),purchase:(orderId,amount)=>{if(/^[0-9a-f-]{36}$/i.test(orderId))track('Purchase',orderId,Number(amount)/100)}};
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(button&&/adicionar.{0,20}carrinho|comprar agora/i.test(button.textContent||'')&&['/produto/autobar','/produto/agrobar'].includes(location.pathname))setTimeout(()=>track('AddToCart',crypto.randomUUID(),cartValue()),200)},{capture:true});
  addEventListener('online',()=>void flush());setInterval(()=>void flush(),30000);addEventListener('popstate',route);addEventListener('pageshow',()=>{route();void flush()});route();void flush();
})();
