(() => {
  if (['localhost','127.0.0.1'].includes(location.hostname) || window.autobarMarketing) return;
  const tiktokPixel='DAT8TNJC77U5PB60DTT0',metaPixel='969483765461099',products={autobar:'cc63486e-33dc-445a-acdf-8f93cdac3cf8',agrobar:'c4a64980-0d6e-4f27-a79f-db44118b2d5b'},prefix='autobar-marketing:';
  const seen=id=>sessionStorage.getItem(prefix+id)==='1',mark=id=>sessionStorage.setItem(prefix+id,'1');
  !function(w,d,t){w.TiktokAnalyticsObject=t;let q=w[t]=w[t]||[];q.methods=['page','track','identify','instances','debug','on','off','once','ready','alias','group','enableCookie','disableCookie','holdConsent','revokeConsent','grantConsent'];q.setAndDefer=function(target,name){target[name]=function(){target.push([name].concat(Array.prototype.slice.call(arguments,0)))}};for(let i=0;i<q.methods.length;i++)q.setAndDefer(q,q.methods[i]);q.instance=function(id){let instance=q._i[id]||[];for(let i=0;i<q.methods.length;i++)q.setAndDefer(instance,q.methods[i]);return instance};q.load=function(id){let el=d.createElement('script');q._i=q._i||{};q._i[id]=[];el.async=true;el.src='https://analytics.tiktok.com/i18n/pixel/events.js?sdkid='+id+'&lib='+t;d.head.append(el)};q.load(tiktokPixel);q.page()}(window,document,'ttq');
  !function(w,d,s,u){if(w.fbq)return;let f=w.fbq=function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments)};if(!w._fbq)w._fbq=f;f.push=f;f.queue=[];f.loaded=true;f.version='2.0';let el=d.createElement(s);el.async=true;el.src=u;d.head.append(el)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
  window.fbq('init',metaPixel);window.fbq('trackSingle',metaPixel,'PageView');
  const cartItems=()=>{try{const items=JSON.parse(localStorage.getItem('store:cart')||'[]');return Array.isArray(items)?items:[]}catch{return []}};
  const currentSlug=()=>location.pathname==='/produto/agrobar'?'agrobar':'autobar';
  const props=amount=>{const slugs=location.pathname==='/checkout'||location.pathname==='/pagamento-pix'?[...new Set(cartItems().map(item=>item.slug).filter(slug=>products[slug]))]:[currentSlug()];const ids=slugs.map(slug=>products[slug]);return {content_id:ids[0]||products.autobar,content_ids:ids.length?ids:[products.autobar],content_type:'product',currency:'BRL',...(Number.isFinite(amount)&&amount>0?{value:amount}:{}),product_name:slugs.map(slug=>slug==='agrobar'?'AgroBar':'GelaBar').join(' + ')||'GelaBar',store_name:'GelaBar'}};
  const cartValue=()=>{const cents=cartItems().reduce((sum,item)=>sum+Number(item.price)*Number(item.quantity),0);return Number.isFinite(cents)&&cents>0?cents/100:79};
  function track(event,id,amount){if(seen(event+'_'+id))return;const eventId=event+'_'+id,data=props(amount);try{window.ttq.track(event,data,{event_id:eventId})}catch{}try{window.fbq('trackSingle',metaPixel,event,data,{eventID:eventId})}catch{}mark(eventId)}
  const session=()=>{let id=sessionStorage.getItem('autobar_session');if(!id){id=crypto.randomUUID();sessionStorage.setItem('autobar_session',id)}return id};
  function route(){if(['/produto/autobar','/produto/agrobar'].includes(location.pathname))track('ViewContent',session()+'_'+currentSlug(),cartValue());if(location.pathname==='/checkout')track('InitiateCheckout',session(),cartValue())}
  window.autobarMarketing={track,paymentStarted:amount=>track('AddPaymentInfo',session(),Number(amount)/100),purchase:(orderId,amount)=>{if(/^[0-9a-f-]{36}$/i.test(orderId))track('Purchase',orderId,Number(amount)/100)}};
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(button&&/adicionar.{0,20}carrinho|comprar agora/i.test(button.textContent||'')&&['/produto/autobar','/produto/agrobar'].includes(location.pathname))setTimeout(()=>track('AddToCart',session()+'_'+currentSlug(),cartValue()),200)},{capture:true});
  addEventListener('popstate',route);addEventListener('pageshow',route);route();
})();
